###

GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
        "email": "rcgr@live.com.mx",
        "username": "rob2",
        "password": "asdfghjkl"
}