###
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/games

###
PUT http://localhost:3000/api/games/638f809f58d038a145dcb266
Content-Type:  application/json

{
    "description": "The Elder Scrolls V: Skyrim is an action role-playing video game developed by Bethesda Game Studios and published by Bethesda Softworks. It is the fifth main installment in The Elder Scrolls series, following 2006's The Elder Scrolls IV: Oblivion, and was released worldwide for Microsoft Windows, PlayStation 3, and Xbox 360 on November 11, 2011. The game is set 200 years after the events of Oblivion, and takes place in Skyrim, the northernmost province of Tamriel. Its main story focuses on the player's character, the Dragonborn, on their quest to defeat Alduin the World-Eater, a dragon who is prophesied to destroy the world. Over the course of the game, the player completes quests and develops the character by improving skills. The game continues the open world tradition of its predecessors by allowing the player to travel anywhere in the game world at any time, and to ignore or postpone the main storyline indefinitely."
}

###
GET http://localhost:3000/api/games/title/Minecraft

###
POST http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "email": "aylin.aguilar@uabc.edu.mx",
    "username": "Aydelin",
    "password": "asdfghjkl",
    "gender": "female",
    "birthday": "01/07/2003",
    "day_joined": "11/10/2022",
    "games_played": "0"
}

###
GET http://localhost:3000/api/users/636c5d3bee54078b6bf9ca39

###
DELETE http://localhost:3000/api/users/636c5d3bee54078b6bf9ca39

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username": "Aydelin",
    "password": "asdfghjkl"
}

###
PUT http://localhost:3000/api/games/638ef283b9b553740bc68b2c
Content-Type:  application/json

{
    "coverURL": "https://github.com/13-Rob/game_covers/blob/main/704488-among-us-windows-apps-front-cover.png.jpeg"
}

###
POST http://localhost:3000/api/games/new
Content-Type: application/json

{
    "title": "Among Us",
    "release_day": "06/15/2018",
    "genre": "Multiplayer video game",
    "coverURL": "https://www.mobygames.com/images/covers/l/704488-among-us-windows-apps-front-cover.png"
}

###
DELETE http://localhost:3000/api/games/638f808058d038a145dcb25c

###
GET http://localhost:3000/api/news

###
POST http://localhost:3000/api/news
Content-Type: application/json

{
    "title": "Jedi Survivor will be released on March 2023",
    "date": "11/2/2022",
    "description": "The anticipated Star Wars game will be available on stores on March 2023. It is expected that a new trailer for the game will be launched on late December of this year.",
    "source": "The Gamer",
    "image": "https://cdn-www.comingsoon.net/assets/uploads/2022/12/swjs.jpg"
}

###
DELETE http://localhost:3000/api/news/638f8b75b939cb03feeecb42

###
GET http://localhost:3000/api/games

###
GET http://localhost:3000/api/reviews

###
POST http://localhost:3000/api/reviews
Content-Type: application/json

{
    "title": "I don't like it",
    "score": 0,
    "reviewC": "Boring",
    "game": "Mario Kart 8 Deluxe"
}